extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
settings:
  react:
    version: detect
env:
  browser: true
rules:
  comma-dangle:
    - error
    - always-multiline
  object-curly-spacing:
    - error
    - always
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
